# Global LLM configuration - Primary model for complex financial analysis and planning
[llm]
api_type = "gemini"
model = "gemini-2.0-pro-exp-02-05"
api_key = "your-google-api-key"
max_tokens = 20000
temperature = 0.0

# For tasks requiring detailed reasoning explanations
[llm.thinking]
api_type = "gemini"
model = "gemini-2.0-flash-thinking-exp-01-21"
api_key = "your-google-api-key"
max_tokens = 20000
temperature = 0.0

# For image generation (charts, visualizations)
[llm.image]
api_type = "gemini"
model = "gemini-2.0-flash-exp-image-generation"
api_key = "your-google-api-key"
max_tokens = 20000
temperature = 0.7

# Groq configuration for deep reasoning and tool calling
[llm.groq]
api_type = "groq"
model = "qwen-qwq-32b"
api_key = "your-groq-api-key"
base_url = "https://api.groq.com/v1"
max_tokens = 20000
temperature = 0.0

# Azure OpenAI configuration (commented out but preserved)
# [llm.azure]
# api_type = "azure"
# model = "YOUR_MODEL_NAME"
# base_url = "{YOUR_AZURE_ENDPOINT}/openai/deployments/{AZURE_DEPLOYMENT_ID}"
# api_key = "AZURE_API_KEY"
# max_tokens = 8096
# temperature = 0.0
# api_version = "2024-02-15-preview"

# Optional configuration for specific browser configuration
# [browser]
# Whether to run browser in headless mode (default: false)
#headless = false
# Disable browser security features (default: true)
#disable_security = true
# Extra arguments to pass to the browser
#extra_chromium_args = []
# Path to a Chrome instance to use to connect to your normal browser
# e.g. '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
#chrome_instance_path = ""
# Connect to a browser instance via WebSocket
#wss_url = ""
# Connect to a browser instance via CDP
#cdp_url = ""

# Optional configuration, Proxy settings for the browser
# [browser.proxy]
# server = "http://proxy-server:port"
# username = "proxy-username"
# password = "proxy-password"

# Optional configuration, Search settings.
# [search]
# Search engine for agent to use. Default is "Google", can be set to "Baidu" or "DuckDuckGo".
#engine = "Google"